<?php

namespace App\Services;

use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Support\Collection;

class ExportService
{
    public function __construct(private string $generatedBy = '', private array $appliedFilters = []) {}

    /**
     * Export collection to CSV format
     */
    public function toCSV(Collection $data, string $reportTitle): string
    {
        if ($data->isEmpty()) {
            $headers = [];

            return $this->buildCSVHeader($reportTitle, $headers)."No data to export\n";
        }

        $headers = array_keys($data->first());
        $csv = $this->buildCSVHeader($reportTitle, $headers);

        foreach ($data as $row) {
            $csv .= $this->escapeCSVRow($row)."\n";
        }

        return $csv;
    }

    /**
     * Export collection to Excel format
     */
    public function toExcel(Collection $data, string $reportTitle): string
    {
        // For Excel export, we'll create a simple HTML table that can be opened in Excel
        // A full implementation would use a library like PhpSpreadsheet

        if ($data->isEmpty()) {
            $headers = [];
            $html = $this->buildExcelTable($data, $headers, $reportTitle);
            $html .= '<p>No data to export</p>';
        } else {
            $headers = array_keys($data->first());
            $html = $this->buildExcelTable($data, $headers, $reportTitle);
        }

        // Return HTML that Excel can parse
        return $html;
    }

    /**
     * Export collection to PDF format
     */
    public function toPDF(Collection $data, string $reportTitle): string
    {
        if ($data->isEmpty()) {
            $html = '<p>No data to export</p>';
        } else {
            $headers = array_keys($data->first());
            $html = $this->buildPDFContent($data, $headers, $reportTitle);
        }

        // Generate PDF
        $pdf = Pdf::loadHTML($html);

        return $pdf->output();
    }

    /**
     * Build CSV header with metadata
     */
    private function buildCSVHeader(string $reportTitle, array $headers): string
    {
        $csv = "Report: {$reportTitle}\n";
        $csv .= "Generated By: {$this->generatedBy}\n";
        $csv .= 'Generated Date: '.now()->format('Y-m-d H:i:s')."\n";

        if (! empty($this->appliedFilters)) {
            $csv .= "Applied Filters:\n";
            foreach ($this->appliedFilters as $key => $value) {
                if (is_array($value)) {
                    $csv .= "  {$key}: ".implode(', ', $value)."\n";
                } else {
                    $csv .= "  {$key}: {$value}\n";
                }
            }
        }

        $csv .= "\n".implode(',', $this->escapeCSVHeaders($headers))."\n";

        return $csv;
    }

    /**
     * Build Excel table with styling
     */
    private function buildExcelTable(Collection $data, array $headers, string $reportTitle): string
    {
        $html = '<?xml version="1.0" encoding="UTF-8"?>'."\n";
        $html .= '<html xmlns="http://www.w3.org/1999/xhtml">'."\n";
        $html .= '<head><meta charset="UTF-8" /></head>'."\n";
        $html .= '<body>'."\n";

        $html .= "<h2>{$reportTitle}</h2>\n";
        $html .= "<p><strong>Generated By:</strong> {$this->generatedBy}</p>\n";
        $html .= '<p><strong>Generated Date:</strong> '.now()->format('Y-m-d H:i:s')."</p>\n";

        if (! empty($this->appliedFilters)) {
            $html .= "<p><strong>Applied Filters:</strong></p>\n<ul>\n";
            foreach ($this->appliedFilters as $key => $value) {
                if (is_array($value)) {
                    $html .= '<li>'.ucfirst($key).': '.implode(', ', $value)."</li>\n";
                } else {
                    $html .= '<li>'.ucfirst($key).": {$value}</li>\n";
                }
            }
            $html .= "</ul>\n";
        }

        $html .= '<table border="1" cellpadding="5">'."\n";
        $html .= '<thead><tr>';

        foreach ($headers as $header) {
            $html .= '<th><strong>'.ucfirst(str_replace('_', ' ', $header)).'</strong></th>';
        }

        $html .= "</tr></thead>\n<tbody>\n";

        foreach ($data as $row) {
            $html .= '<tr>';
            foreach ($headers as $header) {
                $value = $row[$header] ?? '';
                $html .= '<td>'.$this->formatExportValue($value, true).'</td>';
            }
            $html .= "</tr>\n";
        }

        $html .= "</tbody></table>\n";
        $html .= '</body></html>';

        return $html;
    }

    /**
     * Build PDF content
     */
    private function buildPDFContent(Collection $data, array $headers, string $reportTitle): string
    {
        $html = '<!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <style>
                body { font-family: Arial, sans-serif; margin: 20px; }
                h2 { color: #333; border-bottom: 2px solid #007bff; padding-bottom: 10px; }
                .metadata { margin: 20px 0; background-color: #f8f9fa; padding: 10px; border-radius: 5px; }
                .metadata p { margin: 5px 0; }
                table { width: 100%; border-collapse: collapse; margin-top: 20px; }
                th { background-color: #007bff; color: white; padding: 10px; text-align: left; }
                td { border: 1px solid #ddd; padding: 8px; }
                tr:nth-child(even) { background-color: #f9f9f9; }
                .footer { margin-top: 30px; text-align: center; color: #666; font-size: 12px; }
            </style>
        </head>
        <body>';

        $html .= "<h2>{$reportTitle}</h2>\n";
        $html .= '<div class="metadata">'."\n";
        $html .= "<p><strong>Generated By:</strong> {$this->generatedBy}</p>\n";
        $html .= '<p><strong>Generated Date:</strong> '.now()->format('Y-m-d H:i:s')."</p>\n";

        if (! empty($this->appliedFilters)) {
            $html .= "<p><strong>Applied Filters:</strong></p>\n<ul>\n";
            foreach ($this->appliedFilters as $key => $value) {
                if (is_array($value)) {
                    $html .= '<li>'.ucfirst($key).': '.implode(', ', $value)."</li>\n";
                } else {
                    $html .= '<li>'.ucfirst($key).": {$value}</li>\n";
                }
            }
            $html .= "</ul>\n";
        }

        $html .= "</div>\n";

        $html .= '<table>'."\n";
        $html .= '<thead><tr>';

        foreach ($headers as $header) {
            $html .= '<th>'.ucfirst(str_replace('_', ' ', $header)).'</th>';
        }

        $html .= "</tr></thead>\n<tbody>\n";

        foreach ($data as $row) {
            $html .= '<tr>';
            foreach ($headers as $header) {
                $value = $row[$header] ?? '';
                $html .= '<td>'.$this->formatExportValue($value, true).'</td>';
            }
            $html .= "</tr>\n";
        }

        $html .= "</tbody></table>\n";
        $html .= '<div class="footer"><p>This report was automatically generated by the AHHC Portal</p></div>';
        $html .= '</body></html>';

        return $html;
    }

    /**
     * Escape CSV headers
     */
    private function escapeCSVHeaders(array $headers): array
    {
        return array_map(fn ($header) => '"'.str_replace('"', '""', ucfirst(str_replace('_', ' ', $header))).'"', $headers);
    }

    /**
     * Escape CSV row values
     */
    private function escapeCSVRow(array $row): string
    {
        $escaped = [];
        foreach ($row as $value) {
            if (is_array($value)) {
                $value = implode(', ', $value);
            }
            $escaped[] = '"'.str_replace('"', '""', (string) $value).'"';
        }

        return implode(',', $escaped);
    }

    private function formatExportValue(mixed $value, bool $html = false): string
    {
        if (is_array($value)) {
            $formatted = collect($value)
                ->map(fn ($item) => is_array($item) ? implode(', ', $item) : (string) $item)
                ->implode($html ? '<br/>' : "\n");
            $value = $formatted;
        }

        return $html ? htmlspecialchars((string) $value) : (string) $value;
    }

    /**
     * Create new instance with metadata
     */
    public static function withMetadata(string $generatedBy, array $filters = []): self
    {
        return new self($generatedBy, $filters);
    }
}
