<?php

namespace Tests\Feature;

use App\Enums\ReportType;
use App\Models\User;
use App\Services\ExportService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Collection;
use Tests\TestCase;

class ReportExportTest extends TestCase
{
    use RefreshDatabase;

    public function test_admin_can_export_csv_report_and_log_export(): void
    {
        $admin = User::factory()->create(['role' => 'admin']);

        $response = $this->actingAs($admin)
            ->post('/portal/admin/reports/export', [
                'report_type' => 'Participant Budget',
                'export_format' => 'csv',
            ]);

        $response->assertStatus(200);
        $response->assertHeaderContains('Content-Type', 'text/csv');
        $response->assertHeader('Content-Disposition');
        $response->assertSee('Report: Participant Budget');
        $response->assertSee('Generated By: '.$admin->name);

        $this->assertDatabaseHas('report_export_logs', [
            'user_id' => $admin->id,
            'report_type' => 'Participant Budget',
            'export_format' => 'csv',
            'record_count' => 0,
        ]);
    }

    public function test_admin_can_export_incident_complaint_report(): void
    {
        $admin = User::factory()->create(['role' => 'admin']);

        $response = $this->actingAs($admin)
            ->post('/portal/admin/reports/export', [
                'report_type' => 'Incident / Complaint',
                'export_format' => 'csv',
            ]);

        $response->assertStatus(200);
        $response->assertSee('Report: Incident / Complaint');
    }

    public function test_report_type_options_include_worker_compliance_and_monthly_care_management(): void
    {
        $options = ReportType::options();

        $this->assertSame('Worker Compliance Report', $options['Compliance']);
        $this->assertSame('Monthly Care Management Report', $options['Care Review']);
        $this->assertSame('Incident / Complaint Report', $options['Incident / Complaint']);
    }

    public function test_non_admin_cannot_export_reports(): void
    {
        $user = User::factory()->create(['role' => 'staff']);

        $response = $this->actingAs($user)
            ->post('/portal/admin/reports/export', [
                'report_type' => 'Participant Budget',
                'export_format' => 'csv',
            ]);

        $response->assertStatus(403);
    }

    public function test_export_service_includes_metadata_in_csv_and_excel_outputs(): void
    {
        $collection = new Collection([
            ['name' => 'Alice', 'email' => 'alice@example.com'],
            ['name' => 'Bob', 'email' => 'bob@example.com'],
        ]);

        $service = ExportService::withMetadata('Test Admin', ['participant_id' => 42]);

        $csv = $service->toCSV($collection, 'Dummy Report');
        $this->assertStringContainsString('Generated By: Test Admin', $csv);
        $this->assertStringContainsString('Applied Filters:', $csv);
        $this->assertStringContainsString('participant_id: 42', $csv);

        $excel = $service->toExcel($collection, 'Dummy Report');
        $this->assertStringContainsString('<h2>Dummy Report</h2>', $excel);
        $this->assertStringContainsString('<strong>Generated By:</strong> Test Admin', $excel);
        $this->assertStringContainsString('<li>Participant_id: 42</li>', $excel);
    }

    public function test_export_service_can_generate_pdf_output(): void
    {
        $collection = new Collection([
            ['name' => 'Alice', 'email' => 'alice@example.com'],
        ]);

        $service = ExportService::withMetadata('Test Admin', ['status' => 'active']);
        $pdf = $service->toPDF($collection, 'Dummy PDF Report');

        $this->assertIsString($pdf);
        $this->assertStringStartsWith('%PDF', $pdf);
        $this->assertGreaterThan(0, strlen($pdf));
    }
}
